"""init

Revision ID: de53536facba
Revises: 065d59ec8701
Create Date: 2021-12-26 21:34:09.828996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de53536facba'
down_revision = '065d59ec8701'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
